pipelines:
  default:
    - step:
        name: Install and Build Client
        image: node:20  # Node image for the client step
        caches: 
          - node
        script:
          - cd client
          - npm install
          - npm run build

    - step:
        name: Install and Run Server
        image: python:3.9  # Python image for the server step
        caches:
          - pip
        script:
          - cd server
          - python3 -m pip install --upgrade pip  
          - pip install -r requirements.txt
          - gunicorn -w 4 -b 0.0.0.0:5000 server:app &  # Run in the background
          - echo $! > gunicorn_pid.txt  # Save the PID
          - sleep 5

    - step:
        name: Run Python Tests
        image: python:3.9
        caches:
          - pip
        script:
          - cd server
          - python3 -m pip install --upgrade pip  
          - pip install -r requirements.txt
          - pytest tests/

    - step:
        name: Stop Flask Server
        image: python:3.9
        script:
          - kill $(cat gunicorn_pid.txt)
  pull-requests:
    "**":  # Matches all branches for pull requests
      - step:
          name: Run PR Tests
          script:
            - echo "Running tests for PR"
            - cd client
            - npm install
            - npm run lint   # Run linting on the client code
            - cd ../server
            - pip install -r requirements.txt
            - pytest         # Run tests on the server code
      - step:
          name: Code Coverage
          script:
            - echo "Calculating code coverage"
            - cd server
            - pytest --cov=. 