pipelines:
  default:
    - step:
        name: Install and Build Client
        image: node:20  # Node image for the client step
        caches: 
          - node
        script:
          - cd client
          - npm install
          - npm run build

    - step:
        name: Install and Run Server #and run Tests
        image: python:3.9  # Python image for the server step
        caches:
          - pip
        script:
          - cd server
          - python3 -m pip install --upgrade pip  
          - pip install -r requirements.txt
          - gunicorn -w 4 -b 0.0.0.0:5000 server:app &  # Run in the background
          - echo $! > gunicorn_pid.txt  # Save the PID
          - sleep 5
        #-python -m pytest tests/  # Replace 'tests/' with your actual test directory

  # Create for PR Tests